### ISSUE TITLE
Parameter keyMap: ITableKeyMap of table function does not respect the columns order

### ISSUE THREAD

**Issue by radufilipescu** [carlcalderon/fmt#3]
First of all, thanks for this awsome library!

Object.key(keyMap) does not guarantee the order of the keys. Example:
`Object.keys({ prop1: { label: 'COL-1' }, '3': { label: 'COL-2' }, 1: { label: 'COL-3' }, 'aProp': { label: 'COL-4' } })`
`(4) ["1", "3", "prop1", "aProp"]`

If I need to print a table wich contains column names that are made of digits only, then those columns will be printed before any other column.

The workaround i found is to use a Map<string, any> wrapped inside of a Proxy, like this:

```
const keyMap = new Proxy(new Map([
      ['prop1', { label: 'COL-1' }],
      ['3', { label: 'COL-2' }],
      ['1', { label: 'COL-3' }],
      ['aProp', { label: 'COL-4' }],
    ]), {
      get: function(target, name) {
        return target.get(name as string);
      },
      ownKeys: function(target) {
        //@ts-ignore
        const keys: Array<string> = [...target.keys()];
        return keys;
      },
      getOwnPropertyDescriptor: function(target, key) {
        return { value: target.get(key as string), enumerable: true, configurable: true };
      }
    });
...
const print = table(keyMap as any, printRows, { 
      silent: true, 
      palette: TABLE_PALETTE_DEFAULT,
      padding: 1 
    });
```

The reason being that Map preservers the order of the keys. I also needed a Proxy because internally, this library uses `Object.keys(keyMap)` in order to generate the order of the columns.

One possible fix is to make the keyMap an `Array<{ label: string, format?: (data:any) => string|null}>`.

**Comment by carlcalderon** [comment]
Thank you for higlighting this issue. I'm glad to hear that you find `fmt` useful!

I want to keep the interface as simple as possible for the end user. As I see it, and as you pointed out, an array of the keys is the most obvious way to do it for the user. 

This change would ideally imply a breaking change and thus bump `fmt` to `1.0.0` according to SemVer. However, I'm not comfortable bumping `fmt` to version `1` just yet since there are more things I would like to implement prior to that. I suggest the `table` method should allow for either `Object` or `Array` keymap until version `1` is reached.

Would you be interested in contributing with a PR regarding this?

**Comment by carlcalderon** [comment]
Compromise provided as of `0.3.0` where both key-value `Object` and `Array` can be provided as label maps to `fmt.table()`.
